/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlePractice;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();

        assertTrue(
            "someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod()
            );
    }

    @Test public void testLongestString(){
        String expected = "cat";
        String actual = Library.longestStringInAnArray(new String[]{"cat"});
        assertEquals(expected, actual);

        expected = "lion";
        actual = Library.longestStringInAnArray(new String[]{"cat", "lion"});
    }
}
