/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradlePractice;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    //write a method to return the longest string in an array
    public static String longestStringInAnArray(String[] array){
        // set the longest string to be the first element
        String longestString = array[0];
        // loop over the elements
        for(int i = 0; i < array.length; i++){
            // if one is bigger, update the biggest element
            if(array[i].length() > longestString.length()){
                longestString = array[i];
                //alt + enter
            }
        }
        return longestString;
    }
}
