/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello world, welcome to bitmap.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Bitmap test = new Bitmap("src/assets/mario.bmp", "src/assets/", "mirror-mario.bmp");

//        BufferedImage testImg = null;
//        try {
//            testImg = ImageIO.read(new File("src/assets/mario.bmp"));
//        } catch (IOException e) {
//            e.printStackTrace();
//        }

//        test.bitTransformBlackWhite();
//        test.bitTransformBluify();
        test.mirror();
    }

}
