/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;

public class App {

    public static void main(String[] args) {
        // much help from https://www.baeldung.com/java-http-request
        URL url = null;
        try {
            url = new URL("https://swapi.co/api/people/1?format=json");
        } catch (MalformedURLException e) {
            System.out.println("the URL was incorrectly formatted, give up now");
            return;
        }
        try {
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            BufferedReader in = new BufferedReader(
                    new InputStreamReader(connection.getInputStream()));
            String currentLine = in.readLine();
            while(currentLine != null) {
                System.out.println(currentLine);
                currentLine = in.readLine();
            }
            System.out.println("we did it");
        } catch (IOException e) {
            System.out.println("the internet did not work");
            e.printStackTrace();
        }
    }
}
