/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package alice;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Scanner;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());

        Scanner aliceScanner;

        HashSet<String> names = new HashSet<>();
        names.add("alice");
        names.add("bill");
        names.add("tweedle-dee");
        names.add("hatter");
        names.add("caterpillar");

        // keeps track of each character's count
        HashMap<String, Integer> timesSeen = new HashMap<>();
        for(String name : names){
            timesSeen.put(name, 0);
        }


        {
            try {
                aliceScanner = new Scanner(new File("src/main/resources/alice.txt"));
                while(aliceScanner.hasNext()){
                    // if it is a name that matches what I am looking for
                    // add a count to that name
                    String possibleName = aliceScanner.next().toLowerCase();
                    if(names.contains(possibleName)){
                        System.out.println(possibleName);
                        // if I am in this if statement, I have found a matching character
                        int nameWasSeenCount = timesSeen.get(possibleName);
                        timesSeen.put(possibleName, nameWasSeenCount + 1);
                    }
                }

                for(String character : names){
                    // print their name and times seen
                    int seen = timesSeen.get(character);
                    System.out.println(String.format("%s was seen %d times", character, seen));
                }



            } catch (FileNotFoundException e) {
                System.out.println(e.getLocalizedMessage());
                System.out.println("couldnt find the file");

            }

    }

    //  Take in th aclice file
    // get a list of characters we want to check ahead of time
    // count how many times their name is in the book


    }
}
