/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

public class App {
    public static String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(App.getGreeting());
        // since getFertilizer is a static method, I call it on the class, NOT on an instance
        System.out.println(Flower.getFertilizer());
        // since toSillyString isn't static, we can't call it on the class, we have to create an instance (see below)
//        System.out.println(Flower.toSillyString());

        Flower myFirstFlower = new Flower();
        myFirstFlower.color = "red";
        myFirstFlower.hasThorns = true;
        myFirstFlower.numberOfPetals = 32;
        // can't set properties not defined in the class
        // myFirstFlower.stemLength = 12;
        System.out.println(myFirstFlower.toSillyString());
        Flower mySecondFlower = new Flower(100, "yellow", false);
        System.out.println(mySecondFlower.toSillyString());

        Flower[] flowers = new Flower[]{myFirstFlower, mySecondFlower};
        for(Flower flower : flowers) {
            System.out.println(flower.toSillyString());
        }
    }
}
