/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void dataStructurePlayground(){
        String[] friends = {"Michelle", "Jon", "Sharina", "Jeff", "Ginger"};
        
        for(String name : friends ){
            System.out.println("name = " + name);
        }

        ArrayList<String> family = new ArrayList<>();
        family.add("Ginger");
        family.add("Aaron");
        family.add("Jason");

        for(String famMember : family){
            System.out.println("This is a member of my famalam : " + famMember);
            System.out.println(String.format("This is %s", famMember));
        }

        HashMap<String, Integer> racesWon = new HashMap<>();
        racesWon.put("Mikey Shumacher", 3);
        racesWon.put("Chase", 5);
        racesWon.put("Chase", 1420);

        for( String driver : racesWon.keySet()){
            // racesWon.get(driver); // get lets us retrieve a value racesWon.chase
            System.out.println(String.format(
                    "the driver %s has won %d races",
                    driver,
                    racesWon.get(driver)
            ));
        }

        for(int wins : racesWon.values()){
            System.out.println("wins from .values() : " + wins);
        }

        HashSet<String> iceCreamFlavors = new HashSet<>();
        iceCreamFlavors.add("honey lavender");
        iceCreamFlavors.add("triple fudge chocolate");
        iceCreamFlavors.add("green tea");
        iceCreamFlavors.add("honey lavender");

        for(String iceCream : iceCreamFlavors){
            System.out.println(iceCream);
        }
    }
}
